### ISSUE TITLE
Improving performance for word2vec

### ISSUE THREAD

**Issue by NowayIndustries** [inspirehep/magpie#105]
Hello again,

When I am training my corpus I currently always recalculate the wordvectors, since the articles that my corpusses are based on can contain some very weird words (I mean it's Dutch so what do you expect). My problem with the word2vec calculation is that I only ever see two cores (most of the times only one even) being pegged to a 100% during this stage. It takes about 20 minutes to get the vectors calculated on a 44k text corpus, the training only takes 5 minutes (and uses all 16). The twenty minute mark is determined by the first prints of 'Fitted to XXXXX vectors'.

This is odd because the word2vec.py specifically tells gensim to use 4 workers. So should there not be atleast 4 cores being used? 

Disk IO should not be a problem, I get about 4GB/s write and about 8GB/s read. The corpus that this word2vec performance was measured on only takes up ~600mb total.

So any tips on debugging this issue? 

Disk IO was measured using variants of `time dd if=/dev/zero of=~/testfile1 bs=1024k count=20000` for write, `time dd if=~/testfile1 of=/dev/null bs=1024k count=20000` for read with the count being changed to change the file size (100, 1000, 10000, 20000).

**Comment by jstypka** [comment]
Well, the first thing you can do would be to save the word2vec model and load it every time. You can train it only once and then reuse it, unless you want to tweak some parameters. What I usually do is to aggregate my whole dataset (train, test, everything) and train vectors on it and then reuse it. 

You're right that gensim is hardcoded to use 4 cores, however some settings might be overrun on the OS level e.g. if you're running the system in a Docker container that is exposed to only 2 of them. With regard to disk IO, I would be cautious, because the throughput that you mentioned probably applies to large files, however if you have hundreds of thousands of tiny files that the OS needs to open and close, the bottleneck might be somewhere else.

But the best answer for this you would probably get from the gensim folks, because in Magpie we outsource this task to them pretty much entirely. You can experiment a bit with the [`train_word2vec`](train_word2vec) function or [its in-memory sibling](https://github.com/inspirehep/magpie/blob/master/magpie/base/word2vec.py#L14) to get more intuition.

Hope that helps!

**Comment by NowayIndustries** [comment]
I could alter the way I handle the word2vec model although I'm not sure what sort of complications this would cause, if a word is missing from the vector I would assume it would be bad for magpie. If I am going to alter my training I would probably just make it so I could separately start the training of the word2vec models and run several corpusses at the same time. Then I could still train the models with updated vectors but also optimize away some time. (Actually this might be the best solution in any case, since the 4 cores are hardcoded to gensim)

These corpusses would be updated frequently (perhaps even daily) in order to keep up with the new labels the editors apply to articles. I foresee some specialty words/jargon perhaps being present in the new articles but not the old (some of the labels are people in government for example)

As for the CPU cores; the training of the model that happens subsequently does in fact use all 16 cores, so I would assume there to be no issue with gensim accessing these cores (perhaps another environment setup thing, similar to the theano quirk).
The file performance in python seems fine (I can add 30 texts per second to a corpus, via my API (so more overhead)) although this is just a spot check.

Then again, this 44k text corpus was more of a "I wonder what happens when..." situation then an actual use case for the system, for the foreseeable future anyway. The much more reasonable (in my situation) 17K corpus finished it's vectors in 7 minutes and training in 3. A much more manageable time frame.

The in memory function would be interesting to test, although the 44k corpus already causes 11GB of RAM (virt) to be used during training ;) (that is without using batch_train tough so there's another memory improvement). 

Thanks again for your guidance, I'll be going down the gensim/google rabbit hole now.
