### ISSUE TITLE
Non-txt file support question

### ISSUE THREAD

**Issue by zhiwenchong** [inspirehep/magpie#125]
First of all, thank you for creating this tremendously useful tool. It is an inspired convergence of several good ideas.

My question is: is it easy to add support for non-file-based training data? (I'm guessing a file-based approach is for thread safety?)

At present, for a training dataset of 10m records, I have to generate 20m small files (.txt and .lab) from data already encoded in Parquet. I was wondering if it was possible to read data directly from Parquet/Avro or some other more compact format?

**Comment by jstypka** [comment]
hey @zhiwenchong, that is a good question. The software was designed that way as this was the format we kept our data in at the time. If you have a truly massive dataset, using Parquet/Avro makes sense, but this would require us to add a special reading module that would decompress the files and serve them to the `word2vec` and training modules.

I don't think we'll be adding this support anytime soon as our datasets are not that big and it's a significant amount of work, but if you decide it to write it yourself - make sure to open a PR so that we can add it to the codebase!

**Comment by NowayIndustries** [comment]
Hi, don't take this as an official answer; just giving you my observations based on use of Magpie and the code on the repo.

> My question is: is it easy to add support for non-file-based training data? 

I don't think it would be hard, just tedious and maybe going to require some refractoring so the code stays DRY (dont-repeat-yourself). I'd advocate for adding more '_in_memory' variants of the functions, since that allows for the most flexibility for supporting _other_ data sources (with the obvious trade off being memory use). Although if you really wanted to get your hands dirty you _could_ additionally add `_batch_in_memory` variants :)

__tl;dr:__ It _is_ possible to modify Magpie to change this behaviour, but since the original design was based on files in specific directories you'd be basicly rewriting Magpie to add an `_in_memory`  variant of the important functions.

## The problem
To see why this would be tedious, let's look at what I currently do to train a model (abbreviated for clarity):
```python
model = Magpie()
files = [os.path.join(training_dir, f) for f in os.listdir(training_dir) if f.endswith(".txt")]
results = []
for path in files:
     text = "Not read"
     with open(os.path.join(training_dir, path), 'r') as f:
            text = f.read()
     results.append(Document(path[:-4], os.path.join(training_dir, path), text))
model.word2vec_model = train_word2vec_in_memory(results, vec_dim=vecdim)
model.fit_scaler(training_dir)
model.train(training_dir, labels, test_dir=testing_dir, epochs=epochs, callbacks=callbacks)
self.save(model)
```
So there are 3 Magpie functions we need, one of which has an '_in_memory' variant. This variant simply get a list of Document files ([if you set the text variable of a Document will not do any file reading](https://github.com/inspirehep/magpie/blob/master/magpie/base/document.py#L17)).

The other two would require '_in_memory' variants, so let's take a peek at the code to see how that might be possible:

### fit_scaler
The[ `model.fit_scaler(training_dir)`](https://github.com/inspirehep/magpie/blob/master/magpie/main.py#L256) call is basicly a wrapper for the [Word2Vec fit_scaler](https://github.com/inspirehep/magpie/blob/master/magpie/base/word2vec.py#L59) which simply get's a list of Documents from [util's get_documents](https://github.com/inspirehep/magpie/blob/master/magpie/utils.py#L36). But we already have a list of Documents `results`, so that could perhaps replace the `train_dir` parameter in the '_in_memory' variant of `fit_scaler`.

### train
The train call uses the `train_dir` and `test_dir` variables to call [`get_data_for_model`](https://github.com/inspirehep/magpie/blob/master/magpie/nn/input_data.py#L14) which in turn calls `build_x_and_y` which[ reads all the files in the `file_directory` and creates Document objects](https://github.com/inspirehep/magpie/blob/master/magpie/nn/input_data.py#L72). Conveniently we already have a list of Document object.

 __However__ it also reads the `.lab` files at this point, so this would require a seperate parameter. Maybe an `answers` dictionary you could patch in. Or you could modify Document, to keep the answers for a Document in the same data object as the actual document (this might even be a good change to make to Magpie regardless)
Obviously you'd have to do this for the test_dir aswell.

## The conclusion
> (I'm guessing a file-based approach is for thread safety?)

Probably also (if not more so) for memory use reasons (batch_train is a thing to reduce memory usage)

So basicly the question becomes: 
> do you want to simply generate files (which are cheap, simple and basicly the defacto standard in *nix land so there's lots of tools for them), or do you want to use a ludicrious amount of memory (and spend a bunch of time implementing these changes and mitigating side-effects)?

Also these changes would only cover the way _I_ use Magpie as there's plenty of Magpie code that accepts a `*_dir` argument :)

But don't let me discourage you, just take these as instructions and get to work!

**Comment by zhiwenchong** [comment]
Thanks for the feedback. I'm sure I can write something but I'll need to study the issue a little more first. There are a bunch of different data formats/shapes (CSV, SQL) that could benefit from a simple generic key/value interface. Feel free to close the issue for now.
