### ISSUE TITLE
Request - Not a Issue : Can magpie be used for Keyword Extraction

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#167]
It has been specified in intro section as 
"""
 has been developed at CERN to assign subject categories to High Energy Physics abstracts and extract keywords from them.
""" 
How to extract keywords from a given abstract using Magpie.

**Comment by jstypka** [comment]
You can treat each keyword as a label and then you can frame keyword extraction as a multilabel classification problem. You need to define the keyword vocabulary in advance though.

**Comment by dplutcho** [comment]
Not sure if this is helpful but I am guessing you can directly use word2vec model, which is generated from Gensim via Magpie (magpie.word2vec_model), to extract keywords from documents. One way of solving this problem is outline in this project, though I have no idea if this is the right or best way - https://github.com/bguvenc/keyword_extraction.

**Comment by rajeshkumargp** [comment]
Thanks for suggestions
