### ISSUE TITLE
need your help 

### ISSUE THREAD

**Issue by bjlgcxc** [inspirehep/magpie#71]
can you provide an complete instance including the dataset for mutil-label text classification,please.
Thank you very much!

**Comment by bjlgcxc** [comment]
@jstypka

**Comment by tarvos21** [comment]
I also have a simple question, so I add it, too.
How could I train a model, if I have word embeddings but no scaler?
I have a retrained word2vec words embeddings, which I see from the docs that I can add it into MagpieModel with constructor of `word2vec_model`, but what is a scaler?
Thanks a lot!

**Comment by jstypka** [comment]
hey @tarvos21, we don't have docs for that because it's not a common usecase, but it should be possible.

So you can use [this fuction](https://github.com/inspirehep/magpie/blob/master/magpie/main.py#L232) for fitting the scaler on a directory with your corpus. So first you would create a `MagpieModel` object passing your embeddings in the constructor and then run this function before training. The only parameter is the directory where your training data is stored. Let me know how it works!

**Comment by tarvos21** [comment]
@jstypka thanks, it works cool, I first load the word2vec embeddings, it's in plain text, so I modify the original way to load embedding, by adding an argument `binary=False`.
Then I magpie.fit_scaler(), and got a scaler and was able to save it for later usage. Really wonderful!

Great thanks!
